openapi: 3.0.0
info:
  title: Template
  version: 1.0.0
  description: Test template API
tags:
  - name: auth
    description: Authorization methods
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
        description: New user information
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/RegisterUserResponse"
        "400":
          description: Bad request
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error400"
        "401":
          description: Not authorizated
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error401"
        "404":
          description: Not found
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error404"
        "422":
          description: Incorrect data
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error422"
        "500":
          description: Internal server error
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Error500"
components:
  schemas:
    Error400:
      type: object
      properties:
        status:
          type: boolean
          example: false
        error:
          type: string
          example: Bad request
    Error401:
      type: object
      properties:
        status:
          type: boolean
          example: false
        error:
          type: string
          example: Not authorized
    Error404:
      type: object
      properties:
        status:
          type: boolean
          example: false
        error:
          type: string
          example: Not found
    Error422:
      type: object
      properties:
        status:
          type: boolean
          example: false
        errors:
          type: array
          items:
            type: object
    Error500:
      type: object
      properties:
        status:
          type: boolean
          example: false
        error:
          type: string
          example: Internal server error
    RegisterUserRequest:
      type: object
      properties:
        name:
          type: string
          maximum: 255
          description: User name
        email:
          type: string
          maximum: 255
          description: User email
        password:
          type: string
          minimum: 8
          description: User password
      required:
        - name
        - email
        - password
    RegisterUserResponse:
      type: object
      properties:
        result:
          type: boolean
          example: true
        user:
          type: object
          description: Registered user information
          properties:
            name:
              type: string
            email:
              type: string
            updated_at:
              type: string
            created_at:
              type: string
